name: 'Forward-merge Pull Requests'
description: 'Create a pull requests when merge-forward branches are updated. This is useful when you need multiple support branches and need to keep everything up-to-date. It will not resolve merge conflicts.'
author: 'Nicholas Boll'
branding:
  icon: 'git-merge'
  color: 'orange'
inputs:
  branches:
    description: 'Comma-separated list of branches with a plus sign for a branch that that will be merged into the other branch: "support/v3+support/v4,support/v4+main" will ensure "support/v3" is merged into "support/v4".'
    required: true
  token:
    description: 'Github API Token - must be a write token allowing access to the repo'
    required: false
  body:
    description: 'Body message of the pull request. It is not required'
    required: false
  prefix:
    description: 'Optional prefix to the PR title. Useful if you use some type of semantic commit pull request title validator'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
